# Generated by Django 3.0.6 on 2020-08-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200821_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BooleanField(default=False),
        ),
    ]
